# Generated by Django 5.2.4 on 2025-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='images'),
        ),
    ]
