# Generated by Django 5.2.4 on 2025-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_title_en_alter_pokemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
