# Generated by Django 5.2.4 on 2025-11-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_alter_pokemon_pokemon_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_evolution',
            new_name='previous_evolution',
        ),
    ]
