# Generated by Django 5.2.4 on 2025-11-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_alter_pokemonentity_appeared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(null=True, verbose_name='Дата и время исчезновения покемона'),
        ),
    ]
