# Generated by Django 5.2.4 on 2025-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_alter_pokemon_previous_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Название на англоийском'),
            preserve_default=False,
        ),
    ]
